// Blog Registry Configuration
// This file is auto-generated by the deployment script
// To deploy a new registry, run: npm run deploy:registry

// Default registry process ID (replace with actual deployed process ID)
export const BLOG_REGISTRY_PROCESS_ID = 'p2un0gLaXvUFc8Sm1ArASEPWRNVGzrYkBSr_KHgeLRg';

// Registry configuration
export const REGISTRY_CONFIG = {
  processId: BLOG_REGISTRY_PROCESS_ID,
  name: 'Inkwell Blog Registry',
  version: '1.0.0',
  deployedAt: 'Not deployed yet'
};

// Registry actions
export const REGISTRY_ACTIONS = {
  // Public read-only actions
  INFO: 'Info',
  GET_WALLET_BLOGS: 'Get-Wallet-Blogs',
  GET_BLOG_WALLETS: 'Get-Blog-Wallets',
  CHECK_WALLET_ROLE: 'Check-Wallet-Role',
  GET_REGISTRY_STATS: 'Get-Registry-Stats',
  
  // Blog-only write actions
  REGISTER_WALLET_PERMISSIONS: 'Register-Wallet-Permissions',
  REMOVE_WALLET_PERMISSIONS: 'Remove-Wallet-Permissions',
  UPDATE_WALLET_ROLES: 'Update-Wallet-Roles'
} as const;

// Valid roles
export const VALID_ROLES = {
  DEFAULT_ADMIN: 'DEFAULT_ADMIN_ROLE',
  EDITOR: 'EDITOR_ROLE'
} as const;
